name=UCommandExecutor
version=1.0.0
author=javavirys
maintainer=javavirys
sentence=A lightweight, memory-efficient command executor for Arduino and ESP.
paragraph=Execute functions by string commands using a simple callback system. Works great for Serial, MQTT, or WebSocket interfaces.
category=Communication
url=https://github.com/UDFSmart/UCommandExecutor
architectures=*
includes=UCommandExecutor.h
